export const ACTION = {
  SET_LOCATION_PERMISSION: "SET_LOCATION_PERMISSION",
  SET_IS_LOGGED: "SET_IS_LOGGED",
  SET_USERTYPE: "SET_USERTYPE",
  SET_TOKEN: "SET_TOKEN",
  SET_PICTURES_LOADED: "SET_PICTURES_LOADED",
};
